server:
  port: 8080
  shutdown: graceful

spring:
  cloud:
    loadbalancer:
      enabled: true
    discovery:
      client:
        simple:
          instances:
            cat-service:
              - uri: http://cat-service:8080
            owner-service:
              - uri: http://owner-service:8080
  application:
    name: pedigree-service
  datasource:
    url: jdbc:postgresql://postgres:5432/catclub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      metrics:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
      generate-statistics: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        session.events.log: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    parameters:
      ignoreDuplicateTables: true
      ignoreChecksums: true
      ignoreFailedPreconditions: true
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
    type: caffeine
    metrics:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        metrics:
          enabled: true
      cat-service:
        url: http://cat-service:8080
      owner-service:
        url: http://owner-service:8080
  metrics:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  packages-to-scan: org.catclub.pedigree.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db,diskSpace
        liveness:
          include: ping
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    tags:
      application: ${spring.application.name}
      region: local
    distribution:
      percentiles-histogram:
        http.server.requests: true
        feign.client.requests: true
      percentiles:
        http.server.requests: 0.5,0.75,0.95,0.99
        feign.client.requests: 0.5,0.75,0.95,0.99
      sla:
        http.server.requests: 100ms,500ms,1s,5s
        feign.client.requests: 100ms,500ms,1s,5s

logging:
  level:
    org.springframework.boot.actuate: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: INFO
    feign: DEBUG
    io.micrometer: INFO
    org.hibernate.stat: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/catclub
    username: postgres
    password: postgres
  feign:
    client:
      config:
        cat-service:
          url: http://cat-service:8080
        owner-service:
          url: http://owner-service:8080
  jpa:
    properties:
      hibernate:
        generate-statistics: true
  cache:
    metrics:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: pedigree-service
      paths-to-match: /api/pedigrees/**
      packages-to-scan: org.catclub.pedigree.controller
  default-produces-media-type: application/json