server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      enabled: true
    discovery:
      client:
        simple:
          instances:
            cat-service:
              - uri: http://cat-service:8082
            owner-service:
              - uri: http://owner-service:8081
  application:
    name: pedigree-service
  datasource:
    url: jdbc:postgresql://postgres:5432/catclub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    parameters:
      ignoreDuplicateTables: true
      ignoreChecksums: true
  spring:
    security:
      user:
        name: user
        password: password
      filter:
        dispatcher-types: async, request

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    org.springframework.boot.actuate: DEBUG
    org.springframework.web: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/catclub
    username: postgres
    password: postgres
  feign:
    client:
      config:
        cat-service:
          url: http://cat-service:8082
        owner-service:
          url: http://owner-service:8081
  management:
    endpoints:
      web:
        exposure:
          include: "*"
      base-path: /actuator
    endpoint:
      health:
        show-details: always