server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: owner-service
          uri: http://owner-service:8080  # Внутри сети Docker обращаемся на 8080
          predicates:
            - Path=/api/owners/**

        - id: cat-service
          uri: http://cat-service:8080
          predicates:
            - Path=/api/cats/**

        - id: pedigree-service
          uri: http://pedigree-service:8080
          predicates:
            - Path=/api/pedigrees/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG