server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Основные сервисы
        - id: owner-service
          uri: http://owner-service:8080
          predicates:
            - Path=/api/owners/**

        - id: cat-service
          uri: http://cat-service:8080
          predicates:
            - Path=/api/cats/**

        - id: pedigree-service
          uri: http://pedigree-service:8080
          predicates:
            - Path=/api/pedigrees/**

        # Swagger UI (перенаправляем на owner-service)
        - id: swagger-ui
          uri: http://owner-service:8080
          predicates:
            - Path=/swagger-ui.html
          filters:
            - RewritePath=/swagger-ui.html, /swagger-ui/index.html

        # Swagger ресурсы (для корректной работы UI)
        - id: swagger-resources
          uri: http://owner-service:8080
          predicates:
            - Path=/swagger-resources/**

        # API документация сервисов
        - id: owner-api-docs
          uri: http://owner-service:8080
          predicates:
            - Path=/owner-api/v3/api-docs
          filters:
            - RewritePath=/owner-api/v3/api-docs, /v3/api-docs

        - id: cat-api-docs
          uri: http://cat-service:8080
          predicates:
            - Path=/cat-api/v3/api-docs
          filters:
            - RewritePath=/cat-api/v3/api-docs, /v3/api-docs

        - id: pedigree-api-docs
          uri: http://pedigree-service:8080
          predicates:
            - Path=/pedigree-api/v3/api-docs
          filters:
            - RewritePath=/pedigree-api/v3/api-docs, /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: TRACE