global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'owner-service:8080'
          - 'cat-service:8080'
          - 'pedigree-service:8080'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        regex: '(.*):\d+'
        replacement: '${1}'
        target_label: service

  - job_name: 'prometheus-self'
    static_configs:
      - targets: ['localhost:9090']