server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default
  application:
    name: owner-service
  datasource:
    url: jdbc:postgresql://postgres:5432/catclub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      metric-registry: micrometer
  jpa:
    hibernate:
      ddl-auto: validate
      generate-statistics: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        session.events.log: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    parameters:
      ignoreDuplicateTables: true
      ignoreChecksums: true
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
    type: caffeine
    metrics:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  packages-to-scan: org.catclub.owner.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db,diskSpace
        liveness:
          include: ping
    metrics:
      export:
        jmx:
          enabled: true
    prometheus:
      enabled: true
    endpoint:
      heapdump:
        enabled: true
        sensitive: false
    jmx:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    tags:
      application: ${spring.application.name}
      region: local
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.75,0.95,0.99
      sla:
        http.server.requests: 100ms,500ms,1s,5s

logging:
  level:
    org.springframework.boot.actuate: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: INFO
    io.micrometer: INFO
    org.hibernate.stat: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/catclub
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        generate-statistics: true
  cache:
    metrics:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: owner-service
      paths-to-match: /api/owners/**
      packages-to-scan: org.catclub.owner.controller